import axios from 'axios';
import type {
  GetServerSidePropsContext,
  InferGetServerSidePropsType,
} from 'next';
import { getCsrfToken, useSession } from 'next-auth/react';
import Head from 'next/head';
import type { SubmitHandler } from 'react-hook-form';
import { useForm } from 'react-hook-form';
import { Button, Input } from 'tailwind-joy/components';

export async function getServerSideProps(context: GetServerSidePropsContext) {
  return {
    props: {
      csrfToken: await getCsrfToken(context),
    },
  };
}

type Inputs = {
  username: string;
  password: string;
};

export default function IndexPage({
  csrfToken,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const { data: session } = useSession();
  const { register, handleSubmit } = useForm<Inputs>();
  const onSubmit: SubmitHandler<Inputs> = async ({ username, password }) => {
    try {
      const res = await axios.post('/api/auth/callback/credentials', {
        csrfToken,
        username,
        password,
      });
      console.log(res);
      window.location.reload();
    }
    catch (error) {
      console.error(error);
    }
  };

  return (
    <>
      <Head>
        <title>Next Tailwind Template</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <div
        className="flex min-h-screen flex-col gap-8 px-5 py-8 sm:gap-16 sm:px-12
          sm:py-16 lg:gap-24 lg:px-20 lg:py-24"
      >
        <div>
          {session ? (
            <div>
              Signed in <br />
              <Button
                onClick={async () => {
                  try {
                    const res = await axios.post('/api/auth/signout', {
                      csrfToken,
                    });
                    console.log(res);
                    window.location.reload();
                  }
                  catch (error) {
                    console.error(error);
                  }
                }}
              >
                Sign out
              </Button>
            </div>
          ) : (
            <div className="space-y-4">
              <form
                className="space-y-4"
                onSubmit={handleSubmit(onSubmit)}
              >
                <div className="flex items-center">
                  <span className="w-10">ID</span>
                  <Input {...register('username')} />
                </div>
                <div className="flex items-center">
                  <span className="w-10">PW</span>
                  <Input
                    type="password"
                    {...register('password')}
                  />
                </div>
                <Button type="submit">Sign in</Button>
              </form>
            </div>
          )}
        </div>
      </div>
    </>
  );
}
